### ISSUE TITLE
Ufw rules are not cleaned when host restarts

### ISSUE THREAD

**Issue by mlollo** [shinebayar-g/ufw-docker-automated#12]
Since the solution (implemented in branch  [ufw-update-onrestart](https://github.com/mlollo/ufw-docker-automated/tree/ufw-update-onrestart)) uses a different approach from #7. This is why it needs it's own issue.

For more information see comments [comment1](https://github.com/shinebayar-g/ufw-docker-automated/issues/7#issuecomment-762780104) and [comment2](https://github.com/shinebayar-g/ufw-docker-automated/issues/7#issuecomment-767143956) posted in #7.

**Comment by mlollo** [comment]
After implementing [ufw-threads](https://github.com/mlollo/ufw-docker-automated/tree/ufw-threads) I have a bug in stop.py script. All rules are not cleared.

**Comment by mlollo** [comment]
The branch is up to date with [ufw-comment](https://github.com/shinebayar-g/ufw-docker-automated/issues/7#issuecomment-813555116) idea. It was tested on debian 10.8 docker 20.10.5.
One can argue that ufw-docker-automated is quite slow to keep up if docker containers restart at a fast pace.
This delay depends on the number of ufw rules and spawned containers.
But there is a stability in the long run (could be in minutes if you spawn 50/100 containers).
This could be tested more when spawning a huge number of containers.

If the hosts shutdown unexpectedly and the stop script doesn't do it's job.
It's possible to clean 'ghosts' ufw rules with : `service ufw-docker restart`.

Another idea would be to check at boot if ufw rules are present using the comment prefix, and clean them before doing the start script. In this scenario most of the time ufw rules are cleaned during shutdown, but in case of failure the start script will also check ufw rules and cleaned them.

**Comment by florie1706** [comment]
Same with your Go version. Any chance to get this fixed. I need to clear old rules on a server restart manually right now ;)

**Comment by shinebayar-g** [comment]
Just implemented this logic on program startup, now ufw-docker-automated will go through existing ufw rules and delete 'ghost' rules if container is either not running or not found.
