### ISSUE TITLE
Comments to UFW_ALLOW_FROM

### ISSUE THREAD

**Issue by florie1706** [shinebayar-g/ufw-docker-automated#18]
Hi,

I just found this and it works great. Thank you indeed, that's what I was looking for a long time.
I have a very restricted iptables setting, so my server is just accessible from a bunch of ip ranges out of the internet.
To remember which range belong to which provider I added a individual comment to my iptables.
Would it be possible to have this in your solution too?

As an example I have this for you:
`-A DOCKER-USER -s 87.140.192.0/21 -p tcp -m multiport --dports 80,443 -m comment --comment "Telekom Wifi" -j RETURN` 

So, for me it would be great to have something like this:
```   
      - UFW_MANAGED=true
      - UFW_ALLOW_FROM=192.168.178.0/24;87.140.192.0/16
      - UFW_ALLOW_FROM_COMMENT=LAN;Telekom Wifi
```

or as a one-liner:

``` 
      - UFW_MANAGED=true
      - UFW_ALLOW_FROM=192.168.178.0/24-LAN;87.140.192.0/16-Telekom Wifi
```

Do you think this is possible?

**Comment by shinebayar-g** [comment]
This is now implemented in latest update, will be included in next release. Expected syntax is:
```
UFW_ALLOW_FROM=192.168.178.0/24-LAN;87.140.192.0/16-Telekom Wifi
```
Taking `-` as delimiter of comments.
