### ISSUE TITLE
Handle socket disconnect/reconnect

### ISSUE THREAD

**Issue by shinebayar-g** [shinebayar-g/ufw-docker-automated#23]
In the event of docker socket disconnect, app need to gracefully handle disconnection / reconnection

**Comment by thisisommore** [comment]
Can I give it a try?

**Comment by shinebayar-g** [comment]
Sure, welcome.

**Comment by thisisommore** [comment]
Can you guide me in producing an event such that the docker socket is disconnected?

**Comment by shinebayar-g** [comment]
Yes, first start the docker service, then start ufw-docker-automated service, then stop the docker service. You'll see EOF event is coming from docker socket.

**Comment by thisisommore** [comment]
Hey @shinebayar-g, I have managed to create the event with your help.
Should I wait few seconds before calling `NewClientWithOpts` in main.go, or should I call it immediately?

**Comment by shinebayar-g** [comment]
I think we should wait for some seconds, maybe at least 3 - 5 seconds. And it should behave like waiting for docker socket to be available over and over with that interval forever? At least that was my initial thought. 
Some people may argue this service should crash if docker socket crashes. 

Wdyt?

**Comment by thisisommore** [comment]
> I think we should wait for some seconds, maybe at least 3 - 5 seconds. And it should behave like waiting for docker socket to be available over and over with that interval forever? At least that was my initial thought. 
> Some people may argue this service should crash if docker socket crashes. 
> 
> Wdyt? What makes sense for you?

I agree with you, I think this service should just loop and log since that won't be performance issue, right?

**Comment by shinebayar-g** [comment]
Yeah, correct. Just loop and wait, until it become available. That shouldn't be performance hit. :)

**Comment by thisisommore** [comment]
I have not seen any service crashing or I haven't seen what happens when linux sevice has an error, but I think they will be running even after recoverable error like this, since at each boot the enabled service has to start :)

**Comment by thisisommore** [comment]
> Yeah, correct. Just loop and wait, until it become available. That shouldn't be performance hit. :)

So we going for it? :D
