### ISSUE TITLE
Issue root authorization during usage

### ISSUE THREAD

**Issue by itchy2** [shinebayar-g/ufw-docker-automated#28]
Hi all,

first of all I must say this is a great project. So many thanks for all your time invested in here.

I have an issue during runtime (docker-compose up). The firewall rules are not activated, so I checked the logs:
`Sep 20 21:28:54 holger-ab350mds3h ufw-docker-automated[12848]: ufw-docker-automated: Adding rule: /usr/sbin/ufw route allow proto tcp from any to 192.168.32.2 port 80 comment npm-app:d9f340c4f214`

`Sep 20 21:28:54 holger-ab350mds3h ufw-docker-automated[12848]: ufw: exit status 1 ERROR: Es werden Root-Rechte benÃ¶tigt, um dieses Skript auszufÃ¼hren` to translate it: ufw requires root access.

As my ubuntu server is not equiped with user root I have modified my sudoers file:

`myuser     ALL = NOPASSWD: /usr/local/bin/ufw-docker-automated, /usr/sbin/ufw`

also tried the "long version"

`myuser     ALL = NOPASSWD: /usr/local/bin/ufw-docker-automated`
`myuser     ALL = NOPASSWD: /usr/sbin/ufw`

Does anybody has an Idea about the issue?

Thanks and kind regards
Itchy2

**Comment by shinebayar-g** [comment]
Hi. I see the problem. So you're not using the actual `root` user but user with `sudo` access?

**Comment by itchy2** [comment]
Yes exactly. Ubuntu / Lubuntu does not have a activated root user by default. So you could introduce it, but in general everything works fine with SUDO.
