### ISSUE TITLE
Support host network mode

### ISSUE THREAD

**Issue by shinebayar-g** [shinebayar-g/ufw-docker-automated#4]
It's not directly related to ufw and iptables issue. But since we supported managing ufw firewall rules with docker labels, we could go further and support non bridged network (host). 

For example one could run docker containers with:

```
docker run -d --net=host nginx:alpine 
```

In this case docker doesn't create conflicting IPtables rules, hence no destructive behavior. But ufw still has to managed manually and 
```
docker run -d --net=host -l UFW_MANAGED=TRUE -l "UFW_FROM=192.168.0.2;192.168.1.0/24" nginx:alpine
```
will do nothing. It would be nice to have if the script actually supports this use case too.

**Comment by mlollo** [comment]
It appears that with  `--net=host` we just need to do some regular `ufw allow from` commands instead of `ufw route allow from`. What remains to assert is how to retrieve ports used by the container.

**Comment by mlollo** [comment]
I work on that, I think for now in host network mode we can only handle incoming traffic. 
For outgoing traffic, it's a bit more tricky. Maybe we need to do something like this : 
```
ufw allow out to 192.168.1.0/24 port 80 proto tcp
ufw allow out deny to any
```

**Comment by shinebayar-g** [comment]
Maybe we shouldn't do host network mode, because there is no IPtables involved and users can simply create normal ufw rules. What do you think? 🤔

**Comment by mlollo** [comment]
I agree, this could get confusing because we are touching rules that the user maybe want to manage.
It's doable but it requires that the user understands what it does. I'll let the idea the branch net-host.

**Comment by shinebayar-g** [comment]
Indeed, Let's say doable, but not required. As it would make things over complex.
