### ISSUE TITLE
When container has multiple networks, it only creates one network rules

### ISSUE THREAD

**Issue by rodriciru** [shinebayar-g/ufw-docker-automated#44]
Hi.
First, I must say I don't understand iptables, so maybe this is correct.
I have a reverse proxy which has 2 networks (one has more priority over the other)
When I launch your program, only one of these networks is created, and the other is deleted if already exist.
Is correct this behavior?

```
 networks:
            proxy:                
                priority: 1000
            crowdsec:
```
```
ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22/tcp                     ALLOW IN    Anywhere
[ 2] 80/tcp                     ALLOW IN    Anywhere
[ 3] 443                        ALLOW IN    Anywhere
[ 4] 172.18.0.5 443/tcp         ALLOW FWD   Anywhere                   # traefik-traefik-1:0baf661347fb
[ 5] 172.18.0.5 80/tcp          ALLOW FWD   Anywhere                   # traefik-traefik-1:0baf661347fb
[ 6] 22/tcp (v6)                ALLOW IN    Anywhere (v6)
[ 7] 80/tcp (v6)                ALLOW IN    Anywhere (v6)
[ 8] 443 (v6)                   ALLOW IN    Anywhere (v6)
```
As you can see I should have 2 more rules like 4 and 5 but with IP 172.22.0.2 for example

**Comment by shinebayar-g** [comment]
Hi @rodriciru If I understand you correctly are we talking about multiple docker networks?

**Comment by rodriciru** [comment]
Yes, I have a composer with many services and one of them belongs to 2
networks

**Comment by rodriciru** [comment]
How about this?
Can you look at it?

**Comment by shinebayar-g** [comment]
After #46 I'll look into this, thanks.

**Comment by kforeverisback** [comment]
Hey @shinebayar-g, thank you for this awesome project.
It's been useful for my home server!

I needed the multi-network support, so I've implemented myself.
I have a branch which is working for multi-networks (tested for default, single, multi-network in docker-network).

https://github.com/kforeverisback/ufw-docker-automated/tree/feature/multi-network

I'll do a quick PR (unless you're planning to do so soon).
